package uk.co.objectconnexions.organiser.cli.example;

import uk.co.objectconnexions.organiser.cli.ActivityContextFactory;
import uk.co.objectconnexions.organiser.cli.Command;
import uk.co.objectconnexions.organiser.cli.CommandResults;
import uk.co.objectconnexions.organiser.cli.ContextStack;
import uk.co.objectconnexions.organiser.cli.Parameters;
import uk.co.objectconnexions.organiser.cli.app.Cli;

public class Example {

	public static void main(String[] args) {
		
		Cli cli = new Cli();
		
		ActivityContextFactory context = cli.getRootContext();
		context.addCommand(new Command() {
			
			@Override
			public void process(ContextStack context, Parameters parameters, CommandResults result) {
				result.append("this is the result generated by the command with parameters " + parameters.getAll());
				
			}
			
			@Override
			public String getName() {
				
				return "test";
			}
		});
		
		cli.run(null);

	}

}
